version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:5.0.7

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules:
# version: '3.4'

# services:
#   app:
#     database:
#       image: postgres:12.1
#       volumes:
#         - db_data:/var/lib/postgresql/data
#         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     redis:
#       image: redis:5.0.7
#       sidekiq:
#         build:
#           context: .
#           dockerfile: Dockerfile
#         depends_on:
#           - app
#           - database
#           - redis
#         volumes:
#           - .:/app
#           - gem_cache:/usr/local/bundle/gems
#           - node_modules:/app/node_modules
#         env_file: .env
#         environment:
#           RAILS_ENV: development
#         entrypoint: ./entrypoints/sidekiq-entrypoint.sh
#     sidekiq:
#       build:
#         context: .
#         dockerfile: Dockerfile
#       depends_on:
#         - app
#         - database
#         - redis
#       volumes:
#         - .:/app
#         - gem_cache:/usr/local/bundle/gems
#         - node_modules:/app/node_modules
#       env_file: .env
#       environment:
#         RAILS_ENV: development
#       entrypoint: ./entrypoints/sidekiq-entrypoint.sh
#     volumes:
#       gem_cache:
#       db_data:
#       node_modules:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - database
#       - redis
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#       - gem_cache:/usr/local/bundle/gems
#       - node_modules:/app/node_modules
#     env_file: .env
#     environment:
#       RAILS_ENV: development

# version: "3.9"
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/myapp
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db